# Generated by Django 6.0.2 on 2026-02-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("quantity_kg", models.FloatField()),
                ("pickup_address", models.TextField()),
                (
                    "storage_time_hours",
                    models.FloatField(help_text="How long has it been stored?"),
                ),
                (
                    "time_since_cooking_hours",
                    models.FloatField(help_text="Hours since preparation"),
                ),
                (
                    "storage_condition",
                    models.CharField(default="room_temp", max_length=50),
                ),
                ("food_type", models.CharField(default="cooked_meal", max_length=50)),
                ("freshness_score", models.FloatField(blank=True, null=True)),
                ("freshness_label", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("picked_up", "Picked Up"),
                            ("delivered", "Delivered"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
