# Generated by Django 6.0.2 on 2026-04-02 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="confidence",
            field=models.FloatField(
                blank=True, help_text="ML model confidence %", null=True
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="container_type",
            field=models.CharField(blank=True, default="closed", max_length=50),
        ),
        migrations.AddField(
            model_name="donation",
            name="cooking_method",
            field=models.CharField(blank=True, default="boiled", max_length=50),
        ),
        migrations.AddField(
            model_name="donation",
            name="moisture_type",
            field=models.CharField(blank=True, default="moist", max_length=50),
        ),
        migrations.AddField(
            model_name="donation",
            name="smell",
            field=models.CharField(blank=True, default="neutral", max_length=50),
        ),
        migrations.AddField(
            model_name="donation",
            name="texture",
            field=models.CharField(blank=True, default="firm", max_length=50),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["status"], name="donations_d_status_73ca83_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["donor"], name="donations_d_donor_i_b67ace_idx"),
        ),
    ]
