# Generated by Django 5.1.6 on 2026-06-26 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_claimed_at_donation_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='intake, verify, match, logistics, complete, failed', max_length=20)),
                ('final_ngo_id', models.IntegerField(blank=True, null=True)),
                ('final_ngo_name', models.CharField(blank=True, default='', max_length=255)),
                ('decision_trail', models.JSONField(blank=True, default=list)),
                ('ml_freshness_score', models.FloatField(blank=True, null=True)),
                ('ml_confidence', models.FloatField(blank=True, null=True)),
                ('anomalies_found', models.IntegerField(default=0)),
                ('escalations', models.IntegerField(default=0)),
                ('matched_ngos_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='donations.donation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['donation'], name='donations_a_donatio_7caaaa_idx'), models.Index(fields=['status'], name='donations_a_status_7cd343_idx')],
            },
        ),
    ]
