# Generated by Django 5.1.6 on 2026-06-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_alter_agentrun_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
